name: Flutterflow Android Builds

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
        
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '5b12b74' # tag, commit or branch
          channel: 'master'
          cache: true
          
      - name: Resolve issue
        run: flutter pub add intl:^0.18.1
        
      - name: Get dependencies
        run: flutter pub get

      - name: Build aab
        run: flutter build appbundle

      - name: Build apk
        run: flutter build apk --split-per-abi

      # Runs a set of commands using the runners shell
      - name: Upload artifact aab
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/bundle/release
          asset_name: appbundle.zip
          asset_content_type: application/zip
          
      - name: Upload artifact apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/apk/release
          asset_name: apk.zip
          asset_content_type: application/zip
