name: Flutterflow Android Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '5b12b74' # tag, commit or branch
          channel: 'master'
          cache: true
          
      - name: Resolve issue
        run: flutter pub add intl:^0.18.1
        
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk

      - name: Upload the artifacts
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
        with:
          name: ${{ matrix.file }}-mapping.txt
          path: ${{ matrix.file }}-mapping.txt
      - name: Upload the release assets
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.file }}-mapping.txt
          asset_name: ${{ matrix.file }}-mapping.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
