name: Flutterflow Android Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '5b12b74' # tag, commit or branch
          channel: 'master'
          cache: true
          
      - name: Resolve issue
        run: flutter pub add intl:^0.18.1
        
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build apk

      - name: 'Upload APK'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'Built APK'
          path: '${{ steps.build.outputs.built-apk }}'
    # Upload the built APK
